// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulationRetraite0.Data;

#nullable disable

namespace SimulationRetraite0.Migrations.RetraiteSimulations
{
    [DbContext(typeof(RetraiteSimulationsContext))]
    [Migration("20251227222325_AddTableauxAndLignesTableau")]
    partial class AddTableauxAndLignesTableau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimulationRetraite0.Models.Dossier", b =>
                {
                    b.Property<int>("TdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Td_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TdId"));

                    b.Property<DateTime>("TdDateDossier")
                        .HasColumnType("datetime2")
                        .HasColumnName("Td_DateDossier");

                    b.Property<string>("TdDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Td_Description");

                    b.Property<string>("TdNomClient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Td_NomClient");

                    b.Property<string>("TdNomDossier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Td_NomDossier");

                    b.Property<string>("TdPrenomClient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Td_PrenomClient");

                    b.HasKey("TdId");

                    b.ToTable("Dossiers", "dbo");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.LigneTableau", b =>
                {
                    b.Property<int>("LtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Lt_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LtId"));

                    b.Property<string>("LtLibelle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Lt_Libelle");

                    b.Property<int>("LtNumeroLigne")
                        .HasColumnType("int")
                        .HasColumnName("Lt_NumeroLigne");

                    b.Property<int>("LtTabId")
                        .HasColumnType("int")
                        .HasColumnName("Lt_TabId");

                    b.Property<string>("LtValeur1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur1");

                    b.Property<string>("LtValeur10")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur10");

                    b.Property<string>("LtValeur2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur2");

                    b.Property<string>("LtValeur3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur3");

                    b.Property<string>("LtValeur4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur4");

                    b.Property<string>("LtValeur5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur5");

                    b.Property<string>("LtValeur6")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur6");

                    b.Property<string>("LtValeur7")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur7");

                    b.Property<string>("LtValeur8")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur8");

                    b.Property<string>("LtValeur9")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lt_Valeur9");

                    b.HasKey("LtId");

                    b.HasIndex("LtTabId");

                    b.ToTable("LignesTableau", "dbo");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.Tableau", b =>
                {
                    b.Property<int>("TabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tab_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabId"));

                    b.Property<DateTime>("TabDateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tab_DateCreation");

                    b.Property<string>("TabNomTableau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tab_NomTableau");

                    b.Property<int>("TabNumeroTableau")
                        .HasColumnType("int")
                        .HasColumnName("Tab_NumeroTableau");

                    b.Property<int>("TabTdId")
                        .HasColumnType("int")
                        .HasColumnName("Tab_TdId");

                    b.HasKey("TabId");

                    b.HasIndex("TabTdId");

                    b.ToTable("Tableaux", "dbo");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.Tclient", b =>
                {
                    b.Property<int>("TcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TC_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TcId"));

                    b.Property<string>("TcEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_Email");

                    b.Property<string>("TcNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_Nom");

                    b.Property<string>("TcNomDossier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_NomDossier");

                    b.Property<string>("TcPrenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_Prenom");

                    b.HasKey("TcId");

                    b.ToTable("TClients", "dbo");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.LigneTableau", b =>
                {
                    b.HasOne("SimulationRetraite0.Models.Tableau", "Tableau")
                        .WithMany("Lignes")
                        .HasForeignKey("LtTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tableau");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.Tableau", b =>
                {
                    b.HasOne("SimulationRetraite0.Models.Dossier", "Dossier")
                        .WithMany()
                        .HasForeignKey("TabTdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.Tableau", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
