// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulationRetraite0.Data;

#nullable disable

namespace SimulationRetraite0.Migrations.RetraiteSimulations
{
    [DbContext(typeof(RetraiteSimulationsContext))]
    partial class RetraiteSimulationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimulationRetraite0.Models.Dossier", b =>
                {
                    b.Property<int>("TdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Td_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TdId"));

                    b.Property<DateTime>("TdDateDossier")
                        .HasColumnType("datetime2")
                        .HasColumnName("Td_DateDossier");

                    b.Property<string>("TdDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Td_Description");

                    b.Property<string>("TdNomClient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Td_NomClient");

                    b.Property<string>("TdNomDossier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Td_NomDossier");

                    b.Property<string>("TdPrenomClient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Td_PrenomClient");

                    b.HasKey("TdId");

                    b.ToTable("Dossiers", "dbo");
                });

            modelBuilder.Entity("SimulationRetraite0.Models.Tclient", b =>
                {
                    b.Property<int>("TcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TC_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TcId"));

                    b.Property<string>("TcEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_Email");

                    b.Property<string>("TcNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_Nom");

                    b.Property<string>("TcNomDossier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_NomDossier");

                    b.Property<string>("TcPrenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_Prenom");

                    b.HasKey("TcId");

                    b.ToTable("TClients", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
